name: Build Android Debug APK

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Based on package.json engines field
          cache: 'npm' # Cache npm dependencies

      - name: Install Node dependencies
        run: npm ci # Install dependencies including @capacitor/cli

      - name: Sync Capacitor Android project
        # Sync is still needed to update plugins and generate config files, even when loading remote URL
        run: npx cap sync android

      - name: Set up Java (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Popular OpenJDK distribution
          java-version: '21'

      # Note: setup-android action automatically handles SDK setup based on project needs
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK with Gradle
        run: cd android && ./gradlew assembleDebug

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7 # Keep artifact for 7 days